// Code generated by di. DO NOT EDIT.

//go:generate go run -mod=mod github.com/jdkhome/gdk/di/cmd/di
//go:build !diinject
// +build !diinject

package example

// 来自 injector.go 的注入器：

func InitHandlers() []Handler {
	aHandler := AHandler{}
	bHandler := BHandler{}
	v := []Handler{aHandler, bHandler}
	return v
}

func InitUserRepo() Repository[User] {
	userRepo := UserRepo{}
	return userRepo
}

func InitBox() *Box[User] {
	user := ProvideUser()
	box := NewBox[User](user)
	return box
}

func InitStructBox() *Box[User] {
	user := ProvideUser()
	box := &Box[User]{
		Value: user,
	}
	return box
}
